# Generated by Django 6.0 on 2026-01-11 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking_suggestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
