# Generated by Django 6.0 on 2026-01-11 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking_suggestion', '0003_recipe_ingredient1_recipe_ingredient2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredient2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredient3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredient4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredient5',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
