# Generated by Django 6.0 on 2026-01-11 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking_suggestion', '0004_alter_recipe_ingredient2_alter_recipe_ingredient3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredient6',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredient7',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredient8',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
