# Generated by Django 6.0 on 2026-01-12 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking_suggestion', '0005_recipe_ingredient6_recipe_ingredient7_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredient1_embedding',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
